# Generated by Django 5.2.4 on 2025-08-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=223)),
                ('challenge_domain', models.CharField(max_length=255)),
            ],
        ),
    ]
