# Generated by Django 5.2.4 on 2025-08-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
