# Generated by Django 5.2.4 on 2025-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authly', '0002_challenge_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='key',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
