# Generated by Django 5.2.4 on 2025-08-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authly', '0003_challenge_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='key',
            field=models.CharField(max_length=128),
        ),
    ]
