# Generated by Django 5.2.4 on 2025-08-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
