# Generated by Django 5.2.4 on 2025-08-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_website_desc_alter_website_last_updated_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='verified',
            field=models.BooleanField(blank=True, default=False, help_text='Bring back Fakespot!', verbose_name='"Verified" review'),
            preserve_default=False,
        ),
    ]
